
import React from 'react';

export const Footer: React.FC = () => {
  return (
    <footer className="bg-slate-900 border-t border-slate-700/50 mt-12">
      <div className="container mx-auto px-4 py-6 text-center text-slate-500 text-sm">
        <p><strong>Disclaimer:</strong> This application is for entertainment purposes only. The predictions are generated by an AI and are not guaranteed to be winning numbers. Please play responsibly.</p>
        <p className="mt-2">&copy; 2024 AI Lottery Analysis. All Rights Reserved.</p>
      </div>
    </footer>
  );
};
